# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-tradey-market-info-app"
s3_bucket = "tradey-app"
region = "ap-southeast-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
