#on:
#  push:
#    branches:
#      - main
#env:
#  SAM_TEMPLATE: tradey-market-info.yml
#jobs:
#  build-deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout SAM Application Code
#        uses: actions/checkout@v4
#      - name: Setup Python 3.12
#        uses: actions/setup-python@v5
#        with:
#          python-version: '3.12'
#      - name: Run unit tests
#        run: |
#          pip install pytest pytest-asyncio
#          pip install -r requirements.txt
#          pytest -s -vvv ./tests/unit/
#      - uses: aws-actions/setup-sam@v2
#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ap-southeast-1
#      - name: Validate SAM Template File
#        run: sam validate --template ${SAM_TEMPLATE} --lint
#      - name: Setup Docker for cross architecture build
#        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
#      - name: Build SAM Application
#        run: sam build --template ${SAM_TEMPLATE} --use-container
#      - name: Deploy SAM
#        run: sam deploy --config-file samconfig.toml