on:
  push:
    branches:
      - main
env:
  SAM_TEMPLATE: tradey-technical-analysis.yml
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SAM Application Code
        uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Run unit tests
        run: |
          mvn test
      - name: Build project
        run: |
          mvn clean install
      - uses: aws-actions/setup-sam@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Upload JAR file to S3
        uses: aws-actions/amazon-s3-sync-action@v4
        with:
          source: target/
          bucket: dinh-test
      - name: Validate SAM Template File
        run: sam validate --template ${SAM_TEMPLATE} --lint
      - name: Setup Docker for cross architecture build
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Build SAM Application
        run: sam build -t ${SAM_TEMPLATE} --use-container
      - name: Deploy SAM
        run: sam deploy --config-file samconfig.toml